#!/usr/bin/env bash
# A consistent dump of the Ratatoskr database, for restore rather than for reading.
#
#     /usr/local/bin/ratatoskr-dump.sh
#
# `--format=custom`, so `pg_restore` can rebuild selectively and in parallel. A plain SQL dump reads
# nicely and restores as one long transaction that cannot be resumed, which is the wrong trade for
# the only copy of an identity store.
#
# It runs as `postgres` and takes no credential: a dump job that holds a password is a second place
# the password lives.
set -euo pipefail

DATABASE="${RATATOSKR_DATABASE:-ratatoskr}"
DESTINATION="${RATATOSKR_BACKUP_DIR:-/mnt/nvme/backups/ratatoskr}"
KEEP="${RATATOSKR_BACKUP_KEEP:-14}"

# NVMe, never the boot device: this writes hundreds of megabytes on a schedule, and the SD card that
# wears out takes the root filesystem with it.
install -d -m 0700 "$DESTINATION"

stamp="$(date -u +%Y%m%dT%H%M%SZ)"
target="$DESTINATION/$DATABASE-$stamp.dump"

# To a temporary name first, renamed on success. A dump interrupted by a reboot or a full disk would
# otherwise sit in the directory looking exactly like a complete one, and the moment that matters is
# the moment nobody has time to check.
pg_dump --format=custom --compress=zstd --file="$target.partial" "$DATABASE"
mv "$target.partial" "$target"

# The dump is verified by being read, not by existing. `--list` walks the whole archive's table of
# contents, so a truncated or corrupt file fails here rather than during a restore.
pg_restore --list "$target" > /dev/null

# Keep the most recent N. `ls -t` and not `find -mtime`, so the COUNT is the policy: a machine that
# was off for a week must not come back and delete every copy it has.
#
# shellcheck disable=SC2012  # the names are generated by this script, three lines up, from a
# database name and a UTC stamp; there is no non-alphanumeric filename to mishandle, and `find` has
# no ordering by time that does not cost a second sort.
mapfile -t stale < <(ls -1t "$DESTINATION"/"$DATABASE"-*.dump 2>/dev/null | tail -n +"$((KEEP + 1))")
if [ "${#stale[@]}" -gt 0 ]; then
    rm -f -- "${stale[@]}"
fi

# Last, and deliberately noisy: the size is the one number that shows a dump silently becoming empty.
# shellcheck disable=SC2012  # as above.
printf 'ratatoskr-dump: %s (%s bytes), %d kept\n' \
    "$target" "$(stat -c %s "$target")" \
    "$(ls -1 "$DESTINATION"/"$DATABASE"-*.dump 2>/dev/null | wc -l)"
